### ISSUE TITLE
有线网络下打开程序，当前网络显示null

### ISSUE THREAD

**Issue by WenHowe** [air-controller/air-controller-desktop#1]
**黑苹果，网卡 Intel I219V2 PCI Express Gigabit Ethernet**

<img width="802" alt="image" src="https://user-images.githubusercontent.com/6345591/153880088-8979af72-d26b-439d-96cf-819ad8c33dda.png">

<img width="664" alt="image" src="https://user-images.githubusercontent.com/6345591/153881100-171fc5e7-fb0b-4a05-b1df-21ac89d390e0.png">

**Comment by yuanhoujun** [comment]
0.2.0版本已修复此问题。
