### ISSUE TITLE
能否提高传输速度

### ISSUE THREAD

**Issue by Android-wangmeng** [air-controller/air-controller-desktop#13]
网络传输的速度太慢了，500M的光纤，传一个32M的APk，都要传输好久。
希望能优化下！

**Comment by yuanhoujun** [comment]
您好，请问大概需要多久呢

**Comment by Android-wangmeng** [comment]
两三分钟左右。

**Comment by yuanhoujun** [comment]
测试发现，该问题不存在，应用完全使用本地局域网进行数据传输，数据传输主要取决于无线网最大带宽，实际测试48M文件，大概10 ~ 20秒完成传输。

猜想该问题可能是由于手机同时进行其它网络访问，导致网速受限。该问题我会继续观察，感谢你的反馈与支持！
