### ISSUE TITLE
卸载没反应

### ISSUE THREAD

**Issue by ZWXAllen** [air-controller/air-controller-desktop#17]
安卓 13，点击卸载只说在手机端确认。但是手机上无任何反应……且我多选图片集删除时，好像把我所有的图片都删除了。包括相册。相册我是明确没有选的。我只是多选了其他的几个。

**Comment by yuanhoujun** [comment]
感谢反馈，手机具体是什么型号呢

**Comment by yuanhoujun** [comment]
0.4.0版本已修复，需要授予“浮窗访问权限”，以便在后台弹窗卸载窗体
