### ISSUE TITLE
无线网络断开后点击某个文件夹一直显示“loading...”无法退出

### ISSUE THREAD

**Issue by Antisunny** [air-controller/air-controller-desktop#4]
无线网络已经断开，但界面还没有响应，点某个文件夹，界面一直显示“loading...”，必须强制关闭软件重新打开

<img width="1356" alt="截屏2022-05-02 08 52 31" src="https://user-images.githubusercontent.com/2398514/166172288-ffb41d63-6675-4d60-b40b-adbed426ec0f.png">

**Comment by yuanhoujun** [comment]
@Antisunny 已修复，非常感谢你的issue。
