### ISSUE TITLE
部分机型不适配

### ISSUE THREAD

**Issue by nclq** [air-controller/air-controller-desktop#7]
手机机型：vivo x50(v20001A)
手机系统：Android 10(备注：更新originos系统)
手机和电脑同时连接同一网络，在电脑端点击连接手机，手机上显示部分给你无法使用，点击立即修复，也无法修复
![微信图片_20220507121420](https://user-images.githubusercontent.com/105094330/167237774-2a08b6c3-7442-4aeb-80b9-b0981600a421.jpg)

https://user-images.githubusercontent.com/105094330/167237779-68f8f5c1-97c9-4194-84b7-052c31837301.mp4

。

**Comment by yuanhoujun** [comment]
Fixed! #0.3.0
